import { WordPair } from "../../domain/value-objects/WordPair";

export const WORD_PAIRS: WordPair[] = [
  { word: "Pizza", hint: "Food" },
  { word: "Guitar", hint: "Instrument" },
  { word: "Everest", hint: "Mountain" },
  { word: "Titanic", hint: "Movie" },
  { word: "Doctor", hint: "Profession" },
  { word: "Bicycle", hint: "Vehicle" },
  { word: "Elephant", hint: "Animal" },
  { word: "Wedding", hint: "Event" },
  { word: "Volcano", hint: "Natural Landmark" },
  { word: "Cricket", hint: "Sport" },
  { word: "Library", hint: "Building" },
  { word: "Thunderstorm", hint: "Weather" },
  { word: "Samosa", hint: "Snack" },
  { word: "Passport", hint: "Travel Document" },
  { word: "Netflix", hint: "Streaming Service" },
  { word: "Kathmandu", hint: "City" },
  { word: "Chess", hint: "Board Game" },
  { word: "Umbrella", hint: "Rain Gear" },
  { word: "Astronaut", hint: "Space Profession" },
  { word: "Coffee", hint: "Beverage" },
  { word: "Dinosaur", hint: "Prehistoric Creature" },
  { word: "Smartphone", hint: "Electronic Device" },
  { word: "Waterfall", hint: "Natural Landmark" },
  { word: "Birthday", hint: "Celebration" },
  { word: "Pirate", hint: "Fictional Character" },
];
