import { WordPair } from "../../domain/value-objects/WordPair";

// Fatah's "hint" should be related but vaguer/broader than the real word,
// so Fatah can bluff without knowing the exact word.
export const WORD_PAIRS: WordPair[] = [
  { word: "Pizza", hint: "Food" },
  { word: "Guitar", hint: "Instrument" },
  { word: "Everest", hint: "Mountain" },
  { word: "Titanic", hint: "Movie" },
  { word: "Doctor", hint: "Profession" },
  { word: "Bicycle", hint: "Vehicle" },
  { word: "Elephant", hint: "Animal" },
  { word: "Wedding", hint: "Event" },
  { word: "Volcano", hint: "Natural Landmark" },
  { word: "Cricket", hint: "Sport" },
  { word: "Library", hint: "Building" },
  { word: "Thunderstorm", hint: "Weather" },
  { word: "Samosa", hint: "Snack" },
  { word: "Passport", hint: "Travel Document" },
  { word: "Netflix", hint: "Streaming Service" },
  { word: "Kathmandu", hint: "City" },
  { word: "Chess", hint: "Board Game" },
  { word: "Umbrella", hint: "Rain Gear" },
  { word: "Astronaut", hint: "Space Profession" },
  { word: "Coffee", hint: "Beverage" },
  { word: "Dinosaur", hint: "Prehistoric Creature" },
  { word: "Smartphone", hint: "Electronic Device" },
  { word: "Waterfall", hint: "Natural Landmark" },
  { word: "Birthday", hint: "Celebration" },
  { word: "Pirate", hint: "Fictional Character" },
  { word: "Momo", hint: "Food" },
  { word: "Dal Bhat", hint: "Meal" },
  { word: "Gundruk", hint: "Fermented Food" },
  { word: "Dhido", hint: "Traditional Food" },
  { word: "Newari", hint: "Ethnic Community" },
  { word: "Dashain", hint: "Festival" },
  { word: "Tihar", hint: "Festival" },
  { word: "Holi", hint: "Festival" },
  { word: "Pashupatinath", hint: "Temple" },
  { word: "Swayambhunath", hint: "Stupa" },
  { word: "Boudhanath", hint: "Stupa" },
  { word: "Pokhara", hint: "City" },
  { word: "Annapurna", hint: "Mountain" },
  { word: "Langtang", hint: "Valley" },
  { word: "Thamel", hint: "Tourist Area" },
  { word: "Yak", hint: "Animal" },
  { word: "Gorkha", hint: "District" },
  { word: "Khukuri", hint: "Weapon" },
  { word: "Dhaka Topi", hint: "Traditional Cap" },
  { word: "Daura Suruwal", hint: "Traditional Dress" },
  { word: "Sel Roti", hint: "Snack" },
  { word: "Chiya", hint: "Beverage" },
  { word: "Bandh", hint: "Protest" },
  { word: "Load Shedding", hint: "Electricity Problem" },
  { word: "Tempu", hint: "Vehicle" },
  { word: "Sajilo", hint: "Ride App" },
  { word: "Pathao", hint: "Ride App" },
  { word: "Daraz", hint: "Shopping App" },
  { word: "Hamro Patro", hint: "Calendar App" },
  { word: "Buddha", hint: "Religious Figure" },
  { word: "Lumbini", hint: "Birthplace" },
  { word: "Changa", hint: "Kite" },
  { word: "Madal", hint: "Musical Instrument" },
  { word: "Sarangi", hint: "Musical Instrument" },
];
