import { WordPair } from "../../domain/value-objects/WordPair";

// Fatah's "hint" should be related but vaguer/broader than the real word,
// so Fatah can bluff without knowing the exact word.
export const WORD_PAIRS: WordPair[] = [
  { word: "Pizza", hint: "Food" },
  { word: "Guitar", hint: "Instrument" },
  { word: "Everest", hint: "Mountain" },
  { word: "Titanic", hint: "Movie" },
  { word: "Doctor", hint: "Profession" },
  { word: "Bicycle", hint: "Vehicle" },
  { word: "Elephant", hint: "Animal" },
  { word: "Wedding", hint: "Event" },
  { word: "Volcano", hint: "Natural Landmark" },
  { word: "Cricket", hint: "Sport" },
  { word: "Library", hint: "Building" },
  { word: "Thunderstorm", hint: "Weather" },
  { word: "Samosa", hint: "Snack" },
  { word: "Passport", hint: "Travel Document" },
  { word: "Netflix", hint: "Streaming Service" },
  { word: "Kathmandu", hint: "City" },
  { word: "Chess", hint: "Board Game" },
  { word: "Umbrella", hint: "Rain Gear" },
  { word: "Astronaut", hint: "Space Profession" },
  { word: "Coffee", hint: "Beverage" },
  { word: "Dinosaur", hint: "Prehistoric Creature" },
  { word: "Smartphone", hint: "Electronic Device" },
  { word: "Waterfall", hint: "Natural Landmark" },
  { word: "Birthday", hint: "Celebration" },
  { word: "Pirate", hint: "Fictional Character" },
  { word: "Momo", hint: "Food" },
  { word: "Dal Bhat", hint: "Meal" },
  { word: "Gundruk", hint: "Fermented Food" },
  { word: "Dhido", hint: "Traditional Food" },
  { word: "Newari", hint: "Ethnic Community" },
  { word: "Dashain", hint: "Festival" },
  { word: "Tihar", hint: "Festival" },
  { word: "Holi", hint: "Festival" },
  { word: "Pashupatinath", hint: "Temple" },
  { word: "Swayambhunath", hint: "Stupa" },
  { word: "Boudhanath", hint: "Stupa" },
  { word: "Pokhara", hint: "City" },
  { word: "Annapurna", hint: "Mountain" },
  { word: "Langtang", hint: "Valley" },
  { word: "Thamel", hint: "Tourist Area" },
  { word: "Yak", hint: "Animal" },
  { word: "Gorkha", hint: "District" },
  { word: "Khukuri", hint: "Weapon" },
  { word: "Dhaka Topi", hint: "Traditional Cap" },
  { word: "Daura Suruwal", hint: "Traditional Dress" },
  { word: "Sel Roti", hint: "Snack" },
  { word: "Chiya", hint: "Beverage" },
  { word: "Bandh", hint: "Protest" },
  { word: "Load Shedding", hint: "Electricity Problem" },
  { word: "Tempu", hint: "Vehicle" },
  { word: "Sajilo", hint: "Ride App" },
  { word: "Pathao", hint: "Ride App" },
  { word: "Daraz", hint: "Shopping App" },
  { word: "Hamro Patro", hint: "Calendar App" },
  { word: "Buddha", hint: "Religious Figure" },
  { word: "Lumbini", hint: "Birthplace" },
  { word: "Changa", hint: "Kite" },
  { word: "Madal", hint: "Musical Instrument" },
  { word: "Sarangi", hint: "Musical Instrument" },
  // Nepali People
  { word: "Balen", hint: "Politician" },
  { word: "Kulman", hint: "Engineer" },
  { word: "Sandeep Lamichhane", hint: "Cricketer" },
  { word: "Paras Khadka", hint: "Cricketer" },
  { word: "Anmol KC", hint: "Actor" },
  { word: "Dayahang Rai", hint: "Actor" },
  { word: "Rajesh Hamal", hint: "Actor" },
  { word: "Priyanka Karki", hint: "Actress" },
  { word: "Swastima Khadka", hint: "Actress" },
  { word: "Nischal Basnet", hint: "Filmmaker" },
  { word: "Saugat Malla", hint: "Actor" },
  { word: "Pradeep Khadka", hint: "Actor" },
  { word: "Manisha Koirala", hint: "Actress" },
  { word: "Hari Bansha Acharya", hint: "Comedian" },
  { word: "Madan Krishna Shrestha", hint: "Comedian" },
  { word: "Rajendra Lingden", hint: "Politician" },
  { word: "Sher Bahadur Deuba", hint: "Politician" },
  { word: "KP Oli", hint: "Politician" },
  { word: "Pushpa Kamal Dahal", hint: "Politician" },

  // Global Artists & Celebrities
  { word: "Taylor Swift", hint: "Singer" },
  { word: "Drake", hint: "Rapper" },
  { word: "Eminem", hint: "Rapper" },
  { word: "The Weeknd", hint: "Singer" },
  { word: "Beyonce", hint: "Singer" },
  { word: "Rihanna", hint: "Singer" },
  { word: "Ariana Grande", hint: "Singer" },
  { word: "Justin Bieber", hint: "Singer" },
  { word: "Bruno Mars", hint: "Singer" },
  { word: "Ed Sheeran", hint: "Singer" },
  { word: "Billie Eilish", hint: "Singer" },
  { word: "Lady Gaga", hint: "Singer" },
  { word: "Michael Jackson", hint: "Singer" },
  { word: "Elvis Presley", hint: "Singer" },
  { word: "Shakira", hint: "Singer" },
  { word: "Snoop Dogg", hint: "Rapper" },
  { word: "Post Malone", hint: "Singer" },
  { word: "Kanye West", hint: "Rapper" },
  { word: "Leonardo DiCaprio", hint: "Actor" },
  { word: "Tom Cruise", hint: "Actor" },
  { word: "Dwayne Johnson", hint: "Actor" },
  { word: "Johnny Depp", hint: "Actor" },
  { word: "Robert Downey Jr.", hint: "Actor" },
  { word: "Chris Hemsworth", hint: "Actor" },
  { word: "Zendaya", hint: "Actress" },
  { word: "Tom Holland", hint: "Actor" },
  { word: "Will Smith", hint: "Actor" },
  { word: "Jackie Chan", hint: "Actor" },
  { word: "Arnold Schwarzenegger", hint: "Actor" },

  //Gym
  { word: "Roonie Coolman", hint: "BodyBuilding" },
  { word: "Biceps", hint: "BodyBuilding" },
  { word: "Legs", hint: "Body" },

  //Hawadari
  { word: "Mitochondria", hint: "Biology" },

  // Daily Life
  { word: "Toothbrush", hint: "Bathroom Item" },
  { word: "Toothpaste", hint: "Hygiene Product" },
  { word: "Soap", hint: "Cleaning Product" },
  { word: "Shampoo", hint: "Hair Product" },
  { word: "Towel", hint: "Bathroom Item" },
  { word: "Pillow", hint: "Bedding" },
  { word: "Blanket", hint: "Bedding" },
  { word: "Mattress", hint: "Furniture" },
  { word: "Alarm Clock", hint: "Time Device" },
  { word: "Wallet", hint: "Personal Item" },
  { word: "Keys", hint: "Everyday Item" },
  { word: "Backpack", hint: "Bag" },
  { word: "Notebook", hint: "Stationery" },
  { word: "Pen", hint: "Stationery" },
  { word: "Pencil", hint: "Stationery" },
  { word: "Scissors", hint: "Tool" },
  { word: "Mirror", hint: "Household Item" },
  { word: "Remote", hint: "Electronic Device" },
  { word: "Television", hint: "Electronic Device" },
  { word: "Fridge", hint: "Appliance" },
  { word: "Microwave", hint: "Appliance" },
  { word: "Washing Machine", hint: "Appliance" },
  { word: "Fan", hint: "Appliance" },
  { word: "Chair", hint: "Furniture" },
  { word: "Table", hint: "Furniture" },
  { word: "Sofa", hint: "Furniture" },
  { word: "Bed", hint: "Furniture" },
  { word: "Door", hint: "Household Item" },
  { word: "Window", hint: "Household Item" },

  // Food & Drinks
  { word: "Burger", hint: "Fast Food" },
  { word: "French Fries", hint: "Fast Food" },
  { word: "Noodles", hint: "Food" },
  { word: "Pasta", hint: "Food" },
  { word: "Sandwich", hint: "Food" },
  { word: "Ice Cream", hint: "Dessert" },
  { word: "Chocolate", hint: "Sweet" },
  { word: "Cake", hint: "Dessert" },
  { word: "Popcorn", hint: "Snack" },
  { word: "Donut", hint: "Dessert" },
  { word: "Biryani", hint: "Meal" },
  { word: "Pizza", hint: "Fast Food" },
  { word: "Coke", hint: "Beverage" },
  { word: "Red Bull", hint: "Beverage" },
  { word: "Milk", hint: "Beverage" },
  { word: "Juice", hint: "Beverage" },
  { word: "Beer", hint: "Beverage" },
  { word: "Lemonade", hint: "Beverage" },

  // Nature
  { word: "River", hint: "Water Body" },
  { word: "Ocean", hint: "Water Body" },
  { word: "Lake", hint: "Water Body" },
  { word: "Forest", hint: "Natural Area" },
  { word: "Jungle", hint: "Natural Area" },
  { word: "Desert", hint: "Landscape" },
  { word: "Beach", hint: "Landscape" },
  { word: "Island", hint: "Landform" },
  { word: "Cave", hint: "Natural Formation" },
  { word: "Glacier", hint: "Ice Formation" },
  { word: "Rainbow", hint: "Natural Phenomenon" },
  { word: "Sunset", hint: "Natural Phenomenon" },
  { word: "Sunrise", hint: "Natural Phenomenon" },
  { word: "Lightning", hint: "Weather Phenomenon" },
  { word: "Wind", hint: "Natural Force" },
  { word: "Earthquake", hint: "Natural Disaster" },
  { word: "Tornado", hint: "Weather Phenomenon" },
  { word: "Flood", hint: "Natural Disaster" },
  { word: "Landslide", hint: "Natural Disaster" },
  { word: "Cloud", hint: "Weather" },
  { word: "Rain", hint: "Weather" },
  { word: "Snow", hint: "Weather" },
  { word: "Sun", hint: "Celestial Object" },
  { word: "Moon", hint: "Celestial Object" },
  { word: "Star", hint: "Celestial Object" },

  // Animals
  { word: "Lion", hint: "Wild Animal" },
  { word: "Tiger", hint: "Wild Animal" },
  { word: "Bear", hint: "Wild Animal" },
  { word: "Wolf", hint: "Wild Animal" },
  { word: "Fox", hint: "Wild Animal" },
  { word: "Monkey", hint: "Animal" },
  { word: "Giraffe", hint: "Wild Animal" },
  { word: "Zebra", hint: "Wild Animal" },
  { word: "Penguin", hint: "Bird" },
  { word: "Eagle", hint: "Bird" },
  { word: "Parrot", hint: "Bird" },
  { word: "Owl", hint: "Bird" },
  { word: "Crow", hint: "Bird" },
  { word: "Peacock", hint: "Bird" },
  { word: "Dog", hint: "Pet" },
  { word: "Cat", hint: "Pet" },
  { word: "Rabbit", hint: "Pet" },
  { word: "Horse", hint: "Farm Animal" },
  { word: "Cow", hint: "Farm Animal" },
  { word: "Goat", hint: "Farm Animal" },
  { word: "Chicken", hint: "Farm Animal" },
  { word: "Snake", hint: "Reptile" },
  { word: "Crocodile", hint: "Reptile" },
  { word: "Turtle", hint: "Reptile" },
  { word: "Dolphin", hint: "Sea Animal" },
  { word: "Shark", hint: "Sea Animal" },
  { word: "Whale", hint: "Sea Animal" },
  { word: "Octopus", hint: "Sea Animal" },
  { word: "Butterfly", hint: "Insect" },
  { word: "Bee", hint: "Insect" },
  { word: "Ant", hint: "Insect" },
  { word: "Mosquito", hint: "Insect" },

  // Actions
  { word: "Running", hint: "Exercise" },
  { word: "Walking", hint: "Movement" },
  { word: "Jumping", hint: "Movement" },
  { word: "Swimming", hint: "Exercise" },
  { word: "Sleeping", hint: "Rest" },
  { word: "Eating", hint: "Daily Activity" },
  { word: "Drinking", hint: "Daily Activity" },
  { word: "Cooking", hint: "Activity" },
  { word: "Driving", hint: "Transportation" },
  { word: "Dancing", hint: "Performance" },
  { word: "Singing", hint: "Performance" },
  { word: "Laughing", hint: "Reaction" },
  { word: "Crying", hint: "Emotion" },
  { word: "Reading", hint: "Learning Activity" },
  { word: "Writing", hint: "Learning Activity" },
  { word: "Studying", hint: "Learning Activity" },
  { word: "Working", hint: "Activity" },
  { word: "Shopping", hint: "Activity" },
  { word: "Traveling", hint: "Activity" },
  { word: "Talking", hint: "Communication" },
  { word: "Listening", hint: "Communication" },
  { word: "Watching", hint: "Activity" },
  { word: "Thinking", hint: "Mental Activity" },
  { word: "Running", hint: "Movement" },
  { word: "Clapping", hint: "Gesture" },
  { word: "Kissing", hint: "Gesture" },
  { word: "Hugging", hint: "Gesture" },
  { word: "Fighting", hint: "Conflict" },
  { word: "Cooking", hint: "Household Activity" },
  { word: "Cleaning", hint: "Household Activity" },

  // Social Media & Internet
  { word: "Instagram", hint: "Social Media" },
  { word: "Facebook", hint: "Social Media" },
  { word: "TikTok", hint: "Social Media" },
  { word: "YouTube", hint: "Video Platform" },
  { word: "Snapchat", hint: "Social Media" },
  { word: "Twitter", hint: "Social Media" },
  { word: "Reddit", hint: "Online Community" },
  { word: "Discord", hint: "Communication Platform" },
  { word: "WhatsApp", hint: "Messaging App" },
  { word: "Telegram", hint: "Messaging App" },
  { word: "Messenger", hint: "Messaging App" },
  { word: "LinkedIn", hint: "Professional Platform" },
  { word: "Pinterest", hint: "Social Platform" },
  { word: "Twitch", hint: "Streaming Platform" },
  { word: "Spotify", hint: "Streaming Service" },
  { word: "Google", hint: "Search Engine" },
  { word: "Gmail", hint: "Email Service" },
  { word: "Zoom", hint: "Video Platform" },

  // Nepali Places
  { word: "Kathmandu", hint: "Capital City" },
  { word: "Pokhara", hint: "Tourist City" },
  { word: "Lalitpur", hint: "City" },
  { word: "Bhaktapur", hint: "City" },
  { word: "Chitwan", hint: "District" },
  { word: "Lumbini", hint: "Historical Site" },
  { word: "Janakpur", hint: "City" },
  { word: "Biratnagar", hint: "City" },
  { word: "Birgunj", hint: "City" },
  { word: "Dharan", hint: "City" },
  { word: "Butwal", hint: "City" },
  { word: "Hetauda", hint: "City" },
  { word: "Nagarkot", hint: "Tourist Area" },
  { word: "Bandipur", hint: "Tourist Area" },
  { word: "Ghandruk", hint: "Village" },
  { word: "Mustang", hint: "District" },
  { word: "Manang", hint: "District" },
  { word: "Everest Base Camp", hint: "Trekking Destination" },
  { word: "Annapurna Base Camp", hint: "Trekking Destination" },
  { word: "Rara Lake", hint: "Lake" },
  { word: "Phewa Lake", hint: "Lake" },
  { word: "Chitwan National Park", hint: "National Park" },
  { word: "Sagarmatha National Park", hint: "National Park" },
  { word: "Patan Durbar Square", hint: "Historical Site" },
  { word: "Bhaktapur Durbar Square", hint: "Historical Site" },
  { word: "Kathmandu Durbar Square", hint: "Historical Site" },
  { word: "Garden of Dreams", hint: "Garden" },
  { word: "Thamel", hint: "Tourist Area" },
  { word: "Asan", hint: "Market Area" },
  { word: "New Road", hint: "Shopping Area" },
  { word: "Basantapur", hint: "Historical Area" },
];
